### ISSUE TITLE
Issue with Ember 2.2.0 update "No route matches [OPTIONS]"

### ISSUE THREAD

**Issue by fguillen** [cyu/rack-cors#101]
The GET request is solved properly but when I try to update a Ember Model into the Rails backend, the first request that Ember does is a OPTIONS request and looks like the _rack-cors_ is not managing this request because I'm receiving a `No route matches [OPTIONS] ` error.

This is the Chrome XHR console log:

    General:
      Remote Address:127.0.0.1:80
      Request URL:http://reportsdashboard-v2.domain.com.dev/api/reports/aa0724c0-0238-0133-f4f5-0a81e8b09a82
      Request Method:OPTIONS
      Status Code:404 Not Found

    Response Headers
      HTTP/1.1 404 Not Found
      Content-Type: text/html; charset=utf-8
      Content-Length: 32594
      X-Request-Id: ea6b77f0-3f32-4efd-af70-770cb9cf6090
      X-Runtime: 0.608051
      Vary: Origin
      X-Rack-CORS: preflight-hit
      Date: Sat, 21 Nov 2015 21:09:24 GMT
      Connection: keep-alive

    Request Headers
      OPTIONS /api/reports/aa0724c0-0238-0133-f4f5-0a81e8b09a82 HTTP/1.1
      Host: reportsdashboard-v2.domain.com.dev
      Connection: keep-alive
      Pragma: no-cache
      Cache-Control: no-cache
      Access-Control-Request-Method: PUT
      Origin: http://localhost:4200
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
      Access-Control-Request-Headers: accept, content-type
      Accept: */*
      Referer: http://localhost:4200/reports/aa0724c0-0238-0133-f4f5-0a81e8b09a82/charts
      Accept-Encoding: gzip, deflate, sdch
      Accept-Language: en,de;q=0.8,en-US;q=0.6,es;q=0.4,ko;q=0.2,ar;q=0.2,he;q=0.2,et;q=0.2

My middleware config:

    config.middleware.insert_before 0, "Rack::Cors", debug: true, logger: (-> { Rails.logger }) do
      allow do
        origins '*'
        resource '*', 
          :headers => :any, 
          :methods => [:get, :post, :options],
          :credentials => true,
          :max_age => 0
      end
    end

**Comment by fguillen** [comment]
This is the output of `request.env` if I capture the request:

    {"rack.version"=>[1, 2], "rack.input"=>#<StringIO:0x007fea7c2b5480>, "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>false, "rack.multiprocess"=>true, "rack.run_once"=>false, "rack.url_scheme"=>"http", "REQUEST_METHOD"=>"OPTIONS", "PATH_INFO"=>"/api/reports/aa0724c0-0238-0133-f4f5-0a81e8b09a82", "QUERY_STRING"=>"", "SCRIPT_NAME"=>"", "REMOTE_ADDR"=>"127.0.0.1", "SERVER_ADDR"=>"0.0.0.0", "SERVER_NAME"=>"reportsdashboard-v2.daliaresearch.com.dev", "SERVER_PORT"=>"80", "HTTP_HOST"=>"reportsdashboard-v2.daliaresearch.com.dev", "HTTP_CONNECTION"=>"keep-alive", "HTTP_PRAGMA"=>"no-cache", "HTTP_CACHE_CONTROL"=>"no-cache", "HTTP_ACCESS_CONTROL_REQUEST_METHOD"=>"PUT", "HTTP_ORIGIN"=>"http://localhost:4200", "HTTP_USER_AGENT"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36", "HTTP_ACCESS_CONTROL_REQUEST_HEADERS"=>"accept, content-type", "HTTP_ACCEPT"=>"*/*", "HTTP_REFERER"=>"http://localhost:4200/reports/aa0724c0-0238-0133-f4f5-0a81e8b09a82/charts", "HTTP_ACCEPT_ENCODING"=>"gzip, deflate, sdch", "HTTP_ACCEPT_LANGUAGE"=>"en,de;q=0.8,en-US;q=0.6,es;q=0.4,ko;q=0.2,ar;q=0.2,he;q=0.2,et;q=0.2", "REMOTE_PORT"=>"61391", "ORIGINAL_FULLPATH"=>"/api/reports/aa0724c0-0238-0133-f4f5-0a81e8b09a82", "ORIGINAL_SCRIPT_NAME"=>"", "action_dispatch.routes"=>#<ActionDispatch::Routing::RouteSet:0x007fea7c07b458>, "action_dispatch.parameter_filter"=>[:password, :password], "action_dispatch.redirect_filter"=>[], "action_dispatch.secret_token"=>nil, "action_dispatch.secret_key_base"=>"a12ca2a9083fd7d4757ca19cfeca2d8a9a94d17a19cd5dab0a64265a763187f72a05834e834361b89aafe5b9eb0b9f42cf9b10ad8af377675a3b799aee4b8bef_ReportsDashboard", "action_dispatch.show_exceptions"=>true, "action_dispatch.show_detailed_exceptions"=>true, "action_dispatch.logger"=>#<ActiveSupport::Logger:0x007fea7c121150 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007fea7c120f70 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007fea7c1621c8 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x007fea7c120ef8 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<File:/Users/fguillen/Development/Dalia/Product/ReportsDashboardV2/log/development.log>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x007fea7c120e58 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x007fea7c120cf0>>>>, "action_dispatch.backtrace_cleaner"=>#<Rails::BacktraceCleaner:0x007fea7b4a18a8 @filters=[#<Proc:0x007fea7b4a1240@/Users/fguillen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/backtrace_cleaner.rb:10>, #<Proc:0x007fea7b4a1218@/Users/fguillen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/backtrace_cleaner.rb:11>, #<Proc:0x007fea7b4a11f0@/Users/fguillen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/backtrace_cleaner.rb:12>, #<Proc:0x007fea7b4a0ea8@/Users/fguillen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/backtrace_cleaner.rb:24>], @silencers=[#<Proc:0x007fea7b4a0e80@/Users/fguillen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/railties-4.1.9/lib/rails/backtrace_cleaner.rb:15>]>, "action_dispatch.key_generator"=>#<ActiveSupport::CachingKeyGenerator:0x007fea7b4a0cf0 @key_generator=#<ActiveSupport::KeyGenerator:0x007fea7b4a0d18 @secret="a12ca2a9083fd7d4757ca19cfeca2d8a9a94d17a19cd5dab0a64265a763187f72a05834e834361b89aafe5b9eb0b9f42cf9b10ad8af377675a3b799aee4b8bef_ReportsDashboard", @iterations=1000>, @cache_keys=#<ThreadSafe::Cache:0x007fea7b4a0cc8 @backend={}, @default_proc=nil>>, "action_dispatch.http_auth_salt"=>"http authentication", "action_dispatch.signed_cookie_salt"=>"signed cookie", "action_dispatch.encrypted_cookie_salt"=>"encrypted cookie", "action_dispatch.encrypted_signed_cookie_salt"=>"signed encrypted cookie", "action_dispatch.cookies_serializer"=>nil, "ROUTES_70322539977260_SCRIPT_NAME"=>"", "rack.cors"=>#<Rack::Cors::Result:0x007fea7c2c4340 @preflight=true, @hit=true>, "action_dispatch.request_id"=>"25159daf-f3a3-47c7-b307-697341f7be99", "rack.request.cookie_hash"=>{}, "action_dispatch.cookies"=>#<ActionController::RequestForgeryProtection::ProtectionMethods::NullSession::NullCookieJar:0x007fea79848bc0 @key_generator=#<ActiveSupport::CachingKeyGenerator:0x007fea7b4a0cf0 @key_generator=#<ActiveSupport::KeyGenerator:0x007fea7b4a0d18 @secret="a12ca2a9083fd7d4757ca19cfeca2d8a9a94d17a19cd5dab0a64265a763187f72a05834e834361b89aafe5b9eb0b9f42cf9b10ad8af377675a3b799aee4b8bef_ReportsDashboard", @iterations=1000>, @cache_keys=#<ThreadSafe::Cache:0x007fea7b4a0cc8 @backend={}, @default_proc=nil>>, @set_cookies={"locale"=>{:value=>"en", :expires=>Fri, 21 Nov 2025 21:31:06 UTC +00:00, :path=>"/"}}, @delete_cookies={}, @host="reportsdashboard-v2.daliaresearch.com.dev", @secure=false, @options={:signed_cookie_salt=>"", :encrypted_cookie_salt=>"", :encrypted_signed_cookie_salt=>"", :secret_token=>nil, :secret_key_base=>nil, :upgrade_legacy_signed_cookies=>false, :serializer=>nil}, @cookies={"locale"=>"en"}, @committed=false>, "action_dispatch.remote_ip"=>#<ActionDispatch::RemoteIp::GetIp:0x007fea7c2feab8 @env={...}, @check_ip=true, @proxies=/
      ^127\.0\.0\.1$                | # localhost IPv4
      ^::1$                         | # localhost IPv6
      ^fc00:                        | # private IPv6 range fc00
      ^10\.                         | # private IPv4 range 10.x.x.x
      ^172\.(1[6-9]|2[0-9]|3[0-1])\.| # private IPv4 range 172.16.0.0 .. 172.31.255.255
      ^192\.168\.                     # private IPv4 range 192.168.x.x
    /x>, "rack.session"=>{}, "rack.session.options"=>{:skip=>true}, "action_dispatch.request.path_parameters"=>{:controller=>"api/reports", :action=>"show", :id=>"aa0724c0-0238-0133-f4f5-0a81e8b09a82"}, "action_controller.instance"=>#<Api::ReportsController:0x007fea79839e68 @_action_has_layout=true, @_routes=nil, @_headers={"Content-Type"=>"text/html"}, @_status=200, @_request=#<ActionDispatch::Request:0x007fea79839c88 @env={...}, @symbolized_path_params=nil, @filtered_parameters={"controller"=>"api/reports", "action"=>"show", "id"=>"aa0724c0-0238-0133-f4f5-0a81e8b09a82"}, @filtered_env=nil, @filtered_path=nil, @protocol=nil, @port=nil, @method="OPTIONS", @request_method="OPTIONS", @remote_ip=nil, @original_fullpath=nil, @fullpath="/api/reports/aa0724c0-0238-0133-f4f5-0a81e8b09a82", @ip=nil, @uuid=nil>, @_response=#<ActionDispatch::Response:0x007fea79839c60 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x007fea79839b70>, @stream=#<ActionDispatch::Response::Buffer:0x007fea79839a30 @response=#<ActionDispatch::Response:0x007fea79839c60 ...>, @buf=[], @closed=false>, @header={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff"}, @status=200, @sending_file=false, @blank=false, @cv=#<MonitorMixin::ConditionVariable:0x007fea79839968 @monitor=#<ActionDispatch::Response:0x007fea79839c60 ...>, @cond=#<ConditionVariable:0x007fea79839918 @waiters={}, @waiters_mutex=#<Mutex:0x007fea79839878>>>, @committed=false, @sending=false, @sent=false, @content_type=nil, @charset=nil, @cache_control={}, @etag=nil, @request=#<ActionDispatch::Request:0x007fea79839c88 @env={...}, @symbolized_path_params=nil, @filtered_parameters={"controller"=>"api/reports", "action"=>"show", "id"=>"aa0724c0-0238-0133-f4f5-0a81e8b09a82"}, @filtered_env=nil, @filtered_path=nil, @protocol=nil, @port=nil, @method="OPTIONS", @request_method="OPTIONS", @remote_ip=nil, @original_fullpath=nil, @fullpath="/api/reports/aa0724c0-0238-0133-f4f5-0a81e8b09a82", @ip=nil, @uuid=nil>>, @_env={...}, @_prefixes=["api/reports", "api/api", "application"], @_lookup_context=#<ActionView::LookupContext:0x007fea79839378 @details_key=nil, @details={:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby]}, @skip_default_locale=false, @cache=true, @prefixes=["api/reports", "api/api", "application"], @rendered_format=nil, @view_paths=#<ActionView::PathSet:0x007fea798391e8 @paths=[#<ActionView::OptimizedFileSystemResolver:0x007fea7c092b30 @pattern=":prefix/:action{.:locale,}{.:formats,}{+:variants,}{.:handlers,}", @cache=#<ActionView::Resolver::Cache:0x007fea7c092b08 @data=#<ActionView::Resolver::Cache::SmallCache:0x007fea7c092ae0 @backend={}, @default_proc=#<Proc:0x007fea78b069a8@/Users/fguillen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/actionview-4.1.9/lib/action_view/template/resolver.rb:48 (lambda)>>>, @path="/Users/fguillen/Development/Dalia/Product/ReportsDashboardV2/app/views">]>>, @_action_name="show", @_response_body=nil, @marked_for_same_origin_verification=false, @_config={}, @_params={"controller"=>"api/reports", "action"=>"show", "id"=>"aa0724c0-0238-0133-f4f5-0a81e8b09a82"}>, "action_dispatch.request.content_type"=>nil, "action_dispatch.request.request_parameters"=>{}, "rack.request.query_string"=>"", "rack.request.query_hash"=>{}, "action_dispatch.request.query_parameters"=>{}, "action_dispatch.request.parameters"=>{"controller"=>"api/reports", "action"=>"show", "id"=>"aa0724c0-0238-0133-f4f5-0a81e8b09a82"}, "action_dispatch.request.accepts"=>[#<Mime::Type:0x007fea7c40da30 @synonyms=[], @symbol=nil, @string="*/*">], "action_dispatch.request.formats"=>[#<Mime::Type:0x007fea7c40da30 @synonyms=[], @symbol=nil, @string="*/*">], "rack.session.record"=>#<ActiveRecord::SessionStore::Session id: nil, session_id: "2ef23f424cc67de350d4ed952f55d627", data: nil, created_at: nil, updated_at: nil>, "action_dispatch.request.flash_hash"=>nil}

**Comment by cyu** [comment]
Add `:put` to your methods list

**Comment by fguillen** [comment]
:+1:  I was blind!.. Thanks!
