### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by MaxDBN** [cyu/rack-cors#117]
I'm trying to implement google places api in my rails app for finding restaurants near my location. 

This is the error I'm getting when trying to use the function that is fetching the data from the ajax request:

`XMLHttpRequest cannot load . Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

I've added this snippet into my config/application.rb file:

```
    config.middleware.insert_before 0, "Rack::Cors" do
          allow do
            origins '*'
            resource '*', :headers => :any, :methods => [:get, :post, :options]
          end
        end
```

This is the ajax request from my view (coffeescript):

```
        $.ajax
          url: url
          dataType: "json"
          type: "GET"
```

and I've noticed that my request headers remain unchanged. 

(Access-Control-Allow-Origin is not added to request headers)

```
    Request URL: (not relevant)
    Request Method:OPTIONS
    Status Code:200 
    Remote Address: (not relevant)

    Response Headers
    alt-svc:quic=":443"; ma=2592000; v="33,32,31,30,29,28,27,26,25"
    alternate-protocol:443:quic
    cache-control:public, max-age=300
    content-encoding:gzip
    content-length:538
    content-type:application/json; charset=UTF-8
    date:Mon, 16 May 2016 12:59:48 GMT
    expires:Mon, 16 May 2016 13:04:48 GMT
    server:pablo
    status:200
    vary:Accept-Language
    x-frame-options:SAMEORIGIN
    x-xss-protection:1; mode=block

    Request Headers
    Provisional headers are shown
    Access-Control-Request-Headers:accept, x-csrf-token
    Access-Control-Request-Method:GET
    Origin:http://localhost:3000
    Referer:http://localhost:3000/restil/new?
    User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

    Query String Parameters
    view source
    view URL encoded
    location:( not relevant)
    radius:5000
    type:restraunt
    key: (not relevant)
```

jsonp is not an option because it's not supported by places api

Tried everything that's written in these threads: 
- https://github.com/cyu/rack-cors/issues/33
- http://stackoverflow.com/questions/18538549/cant-get-rack-cors-working-in-rails-application (config.middleware.insert 0, Rack::Cors do)
- https://demisx.github.io/rails-api/2014/02/18/configure-accept-headers-cors.html
- http://stackoverflow.com/questions/36406869/add-custom-response-header-with-rack-cors-and-grape (using :expose key)

**Comment by squadette** [comment]
@MaxDBN, 

a) there is a `debug:` option on `use` statement, please try it

b) will you need to use authentication credentials?  If not — disable it with `credentials: false` on `resource` method call, you will have less problems along the way.

c) what's your middleware list?  what does `bundle exec rake middleware` output?

 d) how do you proxy the rails application?  nginx?  something else?  what's in its logs?

**Comment by MaxDBN** [comment]
I found another workaround without using the gem and moved on. Sorry.
If anyone can delete the issue it would be great because it is no longer relevant.

**Comment by MartinKei** [comment]
@MaxDBN Could you please add how you resolved it?

**Comment by MaxDBN** [comment]
@MartinKei 
http://enable-cors.org/server_nginx.html

**Comment by asux** [comment]
Also tried all solutions and gem simply not works!

**Comment by vladlena** [comment]
Same here. I have tried a lot of different combinations.
adn for me -> it is on the top of my middleware list so probably not a conflict with something else...

**Comment by woohoou** [comment]
Same here the gem didn't work

**Comment by MartinKei** [comment]
For my fellow sufferes, here's how I eventually solved the issue. The problem wasn't the gem itself, the problem was that the stack didn't provide a OPTIONS route, like any other framework outside of ruby does (wth?)

So, adding these route in the `routes.rb` solves the issue:

`
  # global options responder -> makes sure OPTION request for CORS endpoints work
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
`

**Comment by cesc1989** [comment]
Thank you @MartinKei

**Comment by cesc1989** [comment]
@MartinKei after all your approach did not work for me. Setting headers in nginx, as the link share by @MaxDBN helped me at last.

Keys values are:
```
add_header 'Access-Control-Max-Age' 1728000;
add_header 'Content-Type' 'text/plain charset=UTF-8';
add_header 'Content-Length' 0;
return 204;
```

when an `OPTIONS` request is done.

**Comment by ozimeu** [comment]
I had the same issue using Rails 4.2 + Grape for API and Ember app on the front. Exactly the same error appeared in the console after upgrading Grape to the newest version a few times (0.19.1). Surprisingly the issue was solved by bumping the Ruby version to 2.2.3, we had 2.2.2 on staging and in production earlier and all the preflight requests ended up with this error. I have no idea why that was a solution in our case, but it definitely helped us. What version of Ruby you're using?

**Comment by mrtibs2000** [comment]
Same problem here. Changing nginx config settings is not an option for me and the routes patch didn't work. Didn't try upgrading Ruby, but can't do that quickly enough. Any other ideas?

**Comment by bparanj** [comment]
This works:

```ruby
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins '*'

    resource '*',
      headers: :any,
      methods: [:get, :post, :put, :patch, :delete, :options, :head]
  end
end
```

This does not work:

```ruby
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins 'http://localhost:3000'

    resource '*',
      headers: :any,
      methods: [:get, :post, :put, :patch, :delete, :options, :head]
  end
end
```
Adding:

```ruby
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
 ```
to routes does not help.

**Comment by hopewise** [comment]
If any one hosting rails on AWS elastic beanstalk, I found those useful:
https://forums.aws.amazon.com/thread.jspa?threadID=179212

**Comment by thebravoman** [comment]
Same here. Having anything different than "*" in origins does not work.

**Comment by cyu** [comment]
@thebravoman are you using elastic beanstalk like others in recent comments?  What I would recommend is passing the `debug: true` option to the middleware.  Doing so will cause the middleware to return a `X-Rack-CORS` header with the results of the origin evaluation.  If you turn it on and don't see it, then the request never reached the middleware.

**Comment by thebravoman** [comment]
@cyu no I am not. I already have the debug in the configuration:

````
    config.middleware.insert_before 0, "Rack::Cors", :debug => true, :logger => (-> { Rails.logger })  do
      allow do
        origins "https://mysite.com"
        resource "/api/v1/resources/*", :headers => :any, :methods => [:get, :head, :options]
      end
    end

````

**Comment by thebravoman** [comment]
@cyu the only way I could get it working is by setting 
````
origins "*"
````
But I don't want to set this. I would like to set specific domain. How could I do this?

**Comment by cyu** [comment]
@thebravoman let's continue this discussion on this other issue:

https://github.com/cyu/rack-cors/issues/33#issuecomment-363439407

I'm closing this issue because the original poster no longer is interested in figuring out the solution, and the issues described here are all over the place.  I encourage anyone still trying to figure out their solution to try create an new issue with as much detail as possible.

**Comment by jattoabdul** [comment]
Has there been any fix or workaround for this error? I am having a similar error where I am getting No route (404) error when making an OPTIONS requests to any of my endpoints.

I am using rails v6, rack-cors ~>1.0

in my application.rb I have
```
config.middleware.insert_before 0, Rack::Cors, debug: true do
      allow do
        origins '*'

        resource '*', headers: :any, expose: ['access-token', 'expiry', 'token-type', 'uid', 'client'], methods: [:get, :post, :put, :patch, :delete, :options, :head]
      end
    end
```

**Comment by richardsondx** [comment]
I ended up on this post while debugging something. If you ended up on this post I recommend to read this:

https://dev.to/effingkay/cors-preflighted-requests--options-method-3024

Understanding the difference between Simple Request and Preflighted requests might help.

**Comment by rhtaylor** [comment]
> This works:
> 
> ```ruby
> Rails.application.config.middleware.insert_before 0, Rack::Cors do
>   allow do
>     origins '*'
> 
>     resource '*',
>       headers: :any,
>       methods: [:get, :post, :put, :patch, :delete, :options, :head]
>   end
> end
> ```
> 
> This does not work:
> 
> ```ruby
> Rails.application.config.middleware.insert_before 0, Rack::Cors do
>   allow do
>     origins 'http://localhost:3000'
> 
>     resource '*',
>       headers: :any,
>       methods: [:get, :post, :put, :patch, :delete, :options, :head]
>   end
> end
> ```
> 
> This also does not work:
> 
> ```ruby
> Rails.application.config.middleware.insert_before 0, Rack::Cors do
>   allow do
>     origins 'localhost:3000', '127.0.0.1:3000'
> 
>     resource '*',
>       headers: :any,
>       methods: [:get, :post, :put, :patch, :delete, :options, :head]
>   end
> end
> ```
> 
> Adding:
> 
> ```ruby
>   match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
> ```
> 
> to routes does not help.

What file are you adding this? I remember 'rack-cors' and it was a green light from there.

**Comment by cyu** [comment]
@jattoabdul Make sure you upgrade to the latest version – older versions require that you handle the `OPTIONS` route.
