### ISSUE TITLE
Really weird (No route matches [OPTIONS]) error. 

### ISSUE THREAD

**Issue by llaine** [cyu/rack-cors#119]
Hi guys,

i'm using rails-api with devise-token-auth and rack-cors but I've experienced a really strange issue so far. 
I'm kind of stuck in here, could you help me? 

Here is my `rake middleware` output

```
[llaine@localhost api2] $ bundle exec rake middleware
use ActionDispatch::Static
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x00555c908f9700>
use Rack::Runtime
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use BetterErrors::Middleware
use Rollbar::Middleware::Rails::RollbarMiddleware
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use Rack::Cors
run NmyApi::Application.routes
```

```
ActionController::RoutingError (No route matches [OPTIONS] "/auth/sign_in"):
```

Here is my application.rb

```

module NmyApi
  class Application < Rails::Application
    config.middleware.use Rack::Cors do
      allow do
        origins '*'
        resource '*',
                 :headers => :any,
                 :expose  => ['access-token', 'expiry', 'token-type', 'uid', 'client'],
                 :methods => [:get, :post, :options, :delete, :put, :patch]
      end
    end
 end
end
```

Gemfile 

```
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

gem 'rails-api'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'active_model_serializers'

gem 'pg'

gem 'puma'

gem 'sidekiq'

gem "mini_magick"

gem 'oj'

gem 'oj_mimic_json'

gem 'activerecord-postgis-adapter'

gem 'geocoder'

gem 'kaminari'

gem 'figaro'

gem 'devise_token_auth'

gem 'omniauth'

gem 'paperclip'

gem 'foreman'

gem 'activerecord-import', '~> 0.4.0'

gem "skylight"

gem "rollbar"

gem 'rack-cors', :require => 'rack/cors'

gem 'faker', '~> 1.6.3'

group :development do
  gem 'better_errors'
  gem 'mailcatcher'

  gem 'pry'
  gem 'pry-rails'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
```

And routes.rb 

```
Rails.application.routes.draw do
  root :to => 'application#index'

  mount_devise_token_auth_for 'User', at: 'auth'

  namespace :v1 do
  ...
  end
end
```

**Comment by pjdavis** [comment]
Have you tried changing your `config.middleware.use` statement to

`config.middleware.insert_before 0, "Rack::Cors" do`

this makes sure the `Rack::Cors` middleware intercepts the request before the rails router does.

**Comment by jadercorrea** [comment]
Any answer on this one? Same here with `config.middleware.insert_before 0, Rack::Cors`.

**Comment by llaine** [comment]
I've changed to `config.middleware.use Rack::Cors do` rebuild my app (i'm using docker to deploy) and now everything works fine so. I guess it was more docker-compose related.

**Comment by waiting-for-dev** [comment]
Be aware that if you are requesting through `OPTIONS` and your request `Origin` header is not in the whitelist or it is the same that the server endpoint, it is ok if the server returns 404, because it will instruct the browser not to perform the following `POST` or whatever request. The important thing is that with a whitelist origin as `Origin`, `OPTIONS` returns 200 and includes given origin in `Access-Control-Allow-Headers`.

You can try with:

```
curl -I -v \
-X OPTIONS \
-H "Origin: yourorigin.com" \
-H "Access-Control-Request-Method: POST" \
-H "Access-Control-Request-Headers: X-Requested-With" \
http://yourdomain.com
```

**Comment by bianjp** [comment]
Meet the same problem with `rack-cors` 0.4.0 and `rails` 5.0.0.1.

@cyu 
The master branch has no such problem, so please release a new version as soon as possible.

**Comment by 31piy** [comment]
I've recently updated from Rails v5.0.1 to v5.0.2, and rack-cors from v0.4.0 to v0.4.1, and faced the same issue. I tried the following to correct this.

My previous `config/initializers/cors.rb`

```ruby
Rails.application.config.middleware.insert_before 0, Rack::Cors, debug: true, logger: (-> { Rails.logger }) do
  allow do
    origins 'localhost'

    resource '*',
             headers: :any,
             credentials: true,
             methods: [:get, :post, :options, :delete, :put, :patch]
  end
end
```
My new `config/initializers/cors.rb`:

```ruby
Rails.application.config.middleware.insert_before 0, Rack::Cors, debug: true, logger: (-> { Rails.logger }) do
  allow do
    origins 'localhost:3000'

    resource '*',
             headers: :any,
             credentials: true,
             methods: [:get, :post, :options, :delete, :put, :patch]
  end
end
```

What I found strange was that I must supply the port in the `origins` to get it run, but previously it was working fine. Any thoughts?

**Comment by mzagaja** [comment]
Just an FYI when I struggled with this message on Friday I threw a lot of things at it before discovering that I was allowing an origin with a trailing slash, and that the origin string in the header lacked the trailing slash. This error makes it seem and feel as if you need to edit routes.rb, but the real issue is that the origin wasn't matching. If I was more experienced with this gem I would submit a pull request to provide better error messages.

**Comment by JerryArns** [comment]
Glad I found this issue, I have newest rails, deploying on heroku, was tearing my hair out trying to figure out why rails was 404ing the preflight options request.

**Comment by JerryArns** [comment]
Is rack cores suppose to serve the preflight options request? If so why would it not be working? Im getting ActionController::RoutingError, 404 not found.
I am using Rails 5.0.2 api, Cors Config as 31piy has, puma server.

**Comment by cyu** [comment]
There are likely a couple of issues going on here, but the original issue has been fixed by #106.  Closing

**Comment by mnussbaumer** [comment]
`post 'identify/:id', to: 'application#identify', as: :identify_cors `
works
`post 'identify/:id', to: 'application#identify', as: :identify_cors, constraints: lambda { |request| request.xhr? }`
gives the missing route message, even if the route is ok. Is this a bug or do I need to insert the middleware somewhere else than 
`config.middleware.insert_before 0, Rack::Cors do`
?

**Comment by devtoro** [comment]
I have the same issue. The thing is that it is working as expected in development and production env, but in staging which has similar configuration to the production env I get the error.

Here is my configuration for cors:

`config.middleware.insert_before 0, Rack::Cors do`
    `allow do`
        ` origins '[host_name]'`
             `resource '*', :headers => :any, :methods => [:put, :patch, :delete, :get, :post, :options]`
        `end`
  `end`

Here are also the logs from puma:

`I, [2018-01-23T14:56:20.890128 #15303]  INFO -- : [c275be97-8c2d-4152-962c-af6c521c0183] Started OPTIONS "/users/sign_in" for 94.65.102.218 at 2018-01-23 14:56:20 +0000
F, [2018-01-23T14:56:20.893478 #15303] FATAL -- : [c275be97-8c2d-4152-962c-af6c521c0183]
F, [2018-01-23T14:56:20.893559 #15303] FATAL -- : [c275be97-8c2d-4152-962c-af6c521c0183] ActionController::RoutingError (No route matches [OPTIONS] "/users/sign_in"):
F, [2018-01-23T14:56:20.893598 #15303] FATAL -- : [c275be97-8c2d-4152-962c-af6c521c0183]
F, [2018-01-23T14:56:20.893643 #15303] FATAL -- : [c275be97-8c2d-4152-962c-af6c521c0183] actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:53:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] railties (5.0.6) lib/rails/rack/logger.rb:36:in ```call_app'
[c275be97-8c2d-4152-962c-af6c521c0183] railties (5.0.6) lib/rails/rack/logger.rb:24:in ```block in call'
[c275be97-8c2d-4152-962c-af6c521c0183] activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in ```block in tagged'
[c275be97-8c2d-4152-962c-af6c521c0183] activesupport (5.0.6) lib/active_support/tagged_logging.rb:26:in ```tagged'
[c275be97-8c2d-4152-962c-af6c521c0183] activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in ```tagged'
[c275be97-8c2d-4152-962c-af6c521c0183] railties (5.0.6) lib/rails/rack/logger.rb:24:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] rack (2.0.3) lib/rack/runtime.rb:22:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] activesupport (5.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] rack (2.0.3) lib/rack/sendfile.rb:111:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] rack-cors (0.4.1) lib/rack/cors.rb:81:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] railties (5.0.6) lib/rails/engine.rb:522:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] rack-cors (0.4.1) lib/rack/cors.rb:81:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] puma (3.9.1) lib/puma/configuration.rb:224:in ```call'
[c275be97-8c2d-4152-962c-af6c521c0183] puma (3.9.1) lib/puma/server.rb:602:in ```handle_request'
[c275be97-8c2d-4152-962c-af6c521c0183] puma (3.9.1) lib/puma/server.rb:435:in ```process_client'
[c275be97-8c2d-4152-962c-af6c521c0183] puma (3.9.1) lib/puma/server.rb:299:in ```block in run'
[c275be97-8c2d-4152-962c-af6c521c0183] puma (3.9.1) lib/puma/thread_pool.rb:120:in ```block in spawn_thread'`

I have tried the "solution" from [#106](https://github.com/cyu/rack-cors/issues/106), but again my  front-end application ( developed with Ember 2.14 ) did not comply with response.

Any ideas?

**Comment by jdevng** [comment]
I saw this same error with
 * devise_token_auth (0.1.43)
 * rails (5.1.6)

but with the exact same setup with the same client request, did not see the error in a server running:

* devise_token_auth (0.1.42)
  * rails (5.1.4)

As others recommended, adding below worked. If the middleware is intercepting, am I missing this addition in the documentation during installation?

Rails.application.config.middleware.insert_before 0, Rack::Cors, debug: true, logger: (-> { Rails.logger }) do
  allow do
    origins 'localhost:3000'

    resource '*',
             headers: :any,
             credentials: true,
             methods: [:get, :post, :options, :delete, :put, :patch]
  end
end

**Comment by aprescott** [comment]
In case it helps anybody else: I was hitting "No route matches [OPTIONS]" in tests (but not development) because I was missing `Access-Control-Request-Method: POST` in my test's request headers. For completeness, my `cors.rb`:

```ruby
allow do
  origins "*"
  resource "/foo-bar", credentials: false, headers: :any, methods: :any
end
```

No `config/routes.rb` catch-all was needed.

**Comment by wstevo4891** [comment]
> In case it helps anybody else: I was hitting "No route matches [OPTIONS]" in tests (but not development) because I was missing `Access-Control-Request-Method: POST` in my test's request headers. For completeness, my `cors.rb`:
> 
> allow do
>   origins "*"
>   resource "/foo-bar", credentials: false, headers: :any, methods: :any
> end
> No `config/routes.rb` catch-all was needed.

Thank you! This was the answer I needed and my specs are passing now.
