### ISSUE TITLE
For Rails app, are config.ru and config/application.rb both needed or one or the other?

### ISSUE THREAD

**Issue by jasonfb** [cyu/rack-cors#122]
question after reading README:

if you have a Rails app, is it necessary to do _both_ the Rack setup in config.ru and the Rails setup in `YourApp::Application` or is it _either-or_ ? 

it would be nice if the README were clarified on that nuance, since a Rails app is by definition sitting on top of Rack.

**Comment by itsterry** [comment]
+1

**Comment by woohoou** [comment]
+1

**Comment by MsUzoAgu** [comment]
hi @jasonfb, @itsterry , @woohoou did any of your guys figure this out?

**Comment by itsterry** [comment]
Nope, sorry. Making CORS work is still on my todo list...

**Comment by cyu** [comment]
No, updating `config.ru` is not necessary in Rails.  I've updated the README to clarify: (https://github.com/cyu/rack-cors/commit/6b1fb8dfed9f499096e38d4f9a7cb30830130810

Thanks!
