### ISSUE TITLE
Cloudfront assets adds CORS only if browser cache is disabled

### ISSUE THREAD

**Issue by fuggfuggfugg** [cyu/rack-cors#127]
This issue occurs with a javascript library I am using [html2canvas](https://github.com/niklasvh/html2canvas). Rails App with assets served via Cloudfront. 

`curl -H "Origin:https://test.beenlightened.com" -I https://d26lsiihbx01xc.cloudfront.net/assets/vitality5-4fa18f58abb96d917717547d6c7b7425.png`

<img width="662" alt="screen shot 2016-10-17 at 11 04 54 am" src="https://cloud.githubusercontent.com/assets/5616123/19443073/9a155368-9459-11e6-8a25-0ae2d36ae77f.png">

However while testing on chrome, it works only when I disable cache in the browser tab. The origin header is passed and cors headers are correctly added. 

<img width="877" alt="screen shot 2016-10-17 at 11 06 50 am" src="https://cloud.githubusercontent.com/assets/5616123/19443241/20e11d3c-945a-11e6-84c2-529ad90744f5.png">

If cache is enabled: 
<img width="946" alt="screen shot 2016-10-17 at 11 10 02 am" src="https://cloud.githubusercontent.com/assets/5616123/19443307/4fca0370-945a-11e6-8536-679b545e2dbc.png">

**Comment by cyu** [comment]
Have you tried clearing your cache?  This will happen if the original cached request didn't have an Origin header. See https://bugs.chromium.org/p/chromium/issues/detail?id=409090

**Comment by fuggfuggfugg** [comment]
@cyu Thanks for replying. I did clear cache before reloading the page.

**Comment by cyu** [comment]
@fuggfuggfugg it seems like chrome is still working off an older cache copy.  That cached content was almost 2 days old.  Can you clear the cache and test again?

**Comment by fuggfuggfugg** [comment]
Tried again after clearing cache, I may have a hunch on what might be happening. Correct me if I'm wrong. 

1:  clearing cache and hard reload: 
<img width="244" alt="screen shot 2016-10-18 at 11 11 57 am" src="https://cloud.githubusercontent.com/assets/5616123/19483855/c250669a-9523-11e6-9b08-a043221f3aed.png">

2: The image in question is loaded via css. 

```
.importance5 {
    background-image: url(//d26lsiihbx01xc.cloudfront.net/assets/vitality5-4fa18f58abb96d917717547d6c7b7425.png);
}
```
![screen shot 2016-10-18 at 11 13 54 am](https://cloud.githubusercontent.com/assets/5616123/19483999/196bb0b0-9524-11e6-9914-c664faca828a.png)

![screen shot 2016-10-18 at 11 14 30 am](https://cloud.githubusercontent.com/assets/5616123/19484008/1f0a06d4-9524-11e6-9bfc-5fc7f220a1b5.png)

I don't see the origin header being passed hence the cors headers are not returned in the Response headers.

3: My third party library then uses this link to redraw inside the canvas. At this time I think it uses the cached image. 

I guess, I can update the library to append timestamp or something to the src

**Comment by cyu** [comment]
@fuggfuggfugg yeah, if no `Origin:` header is passed then that request won't get a CORS response.  I'm guessing that it's not writing the header because it's declared in a CSS file that of the same origin as the image.

**Comment by fuggfuggfugg** [comment]
You're right. The css file and image are served via cloudfront. I shall try adding a timestamp to burn the cache. 

Thanks for the assistance.
