### ISSUE TITLE
:all for method not working

### ISSUE THREAD

**Issue by gnardini** [cyu/rack-cors#129]
Firstly, thanks for putting in all the hard work into this library!

I couldn't find anything about this on the documentation, but I have something like the following and it works great for everything but `DELETE` requests. Any ida why?

```
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins '*'
    resource '*', headers: :any, methods: :all
  end
end
```

**Comment by cyu** [comment]
it should be `methods: :any`
