### ISSUE TITLE
multiple origins with diffrenet resources possible?

### ISSUE THREAD

**Issue by yanivlllev** [cyu/rack-cors#131]
how can i define different resources for different origins?
something like that:

    config.middleware.insert_before 0, Rack::Cors do
     
      allow do
        origins 'http://localhost:3000'
        resource '/api/*', headers: :any, methods: [:get, :post, :options, :put, :delete]
      end

      allow do
        origins 'http://localhost:6000'
        resource '*', headers: :any, methods: [:get, :post, :options, :put, :delete]
      end
      
    end

so it will allow "http://localhost:3000" to access only '/api/*' 
and allow 'http://localhost:6000' to access all?

thanks

**Comment by cyu** [comment]
Yes.
