### ISSUE TITLE
Rails 5.0.1, config.api_only = true, POST request, no filtering happening

### ISSUE THREAD

**Issue by tomgallagher** [cyu/rack-cors#132]
Anyone know anything about this?

I've installed Rack::Cors, it's working because I can see the debugging messages appearing as expected.

However, when I change the origin or methods to block the request it still sails on through.

Tried in development and on Heroku.

**Comment by cyu** [comment]
@tomgallagher Not sure if this is what you mean by, 'sails on through', but the middleware itself doesn't block the gem from forwarding the request onto Rails.  If it doesn't pass the CORS check, `Rack::Cors` doesn't write the headers required by the browser to act on the returned data.  But whatever data Rails would normally return for that route is still returned.

**Comment by tomgallagher** [comment]
Ahhhh, OK totally misunderstood what was going on. Thanks for the reply.
