### ISSUE TITLE
Resource if proc example

### ISSUE THREAD

**Issue by kapso** [cyu/rack-cors#135]
Hey guys, are there any examples of `resource` & `if` proc?

Basically I want to allow cors access to resources only on a particular domain. 

So for example I have 2 subdomains setup on my Rails app.

- test1.mydomain.com/api/v1/*
- test2.mydomain.com/api/v1/*

`resource '/api/*', headers: :any, methods: [:get, :post, :options]` will give access to `api/*` on both domains, but I only want cors access to `test1.mydomain.com`

**Comment by pwim** [comment]
#70 explains how to do it.
