### ISSUE TITLE
rack cors with ionic 3

### ISSUE THREAD

**Issue by ademir10** [cyu/rack-cors#140]
Hi Guys, i'm trying to use this awesome gem with Ionic 3 but i dont know how to do this.
I have a Rails 5 API working and i'd like to implement the ionic v3 in front-end, i found a nice tutorial to do that, but is working in ionic v1, so i dont know how to do the same using ionic v3.
This is the tutorial: https://www.youtube.com/watch?v=M3MnOZmGu3k&t
I just have one problem, how to insert controllers in ionic v3? anybody know how to do? thanks guys!

**Comment by cyu** [comment]
I'm closing this issue because there hasn't been any activity on this issue in a while.
