### ISSUE TITLE
Regular expressions in "origins" are not matching Origin value

### ISSUE THREAD

**Issue by mikx** [cyu/rack-cors#144]
Tried a bunch of different regular expressions like this:

`origins '/my_host_name/'`

Also was using wildcards and backslashes, etc. None of them match, so I get no CORS in responses.

Looking at the rack-cors code, it seems like if you need a quick workaround for your dev environment, here is the solution:

```
    config.middleware.insert_before Warden::Manager, Rack::Cors do
      allow do
        origins Proc::new { true }
        resource '*', :headers => :any, :methods => [:get, :post, :put, :delete, :options], :credentials => true
      end
    end

```

**Comment by cyu** [comment]
@mikx Did you try  `origins /my_host_name` (without quotes)?  I have test cases that suggest that regular expressions are working in that case.

**Comment by mikx** [comment]
Oh, maybe that was the problem. I was always using quotes. My bad, sorry.
