### ISSUE TITLE
'Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response'

### ISSUE THREAD

**Issue by omerdn1** [cyu/rack-cors#145]
I'm getting this error when trying to use the PATCH method:
`XMLHttpRequest cannot load <url>. Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.`
My application.rb file:
```require_relative 'boot'

require 'rails/all'

Bundler.require(*Rails.groups)

module BeyondServer
  class Application < Rails::Application

    config.load_defaults 5.1

    config.middleware.use ActionDispatch::Cookies
    config.middleware.use ActionDispatch::Session::CookieStore


    config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins '*'
        resource '*', :headers => :any, :methods => [:get, :post, :delete, :patch, :options, :head]
      end
    end
  end
end

**Comment by bbruneau** [comment]
@cyu any news?

**Comment by MrHakala** [comment]
Anyone know a workaround? @cyu?

**Comment by cyu** [comment]
@MrHakala I added some tests to the project to make sure PATCH work out of the box – there must be something else going on.  Can you send me more information?  (gem version, url, response headers, etc).
