### ISSUE TITLE
Resources become public

### ISSUE THREAD

**Issue by rafael-tanaka** [cyu/rack-cors#146]
I'm using this in config/application.rb

```
config.middleware.insert_before 0, "Rack::Cors", :debug => true, :logger => (-> { Rails.logger }) do
      allow do
        origins 'https://myclient1.com', 'https://myclient2.com'

        resource '*',
          :headers => :any,
          :methods => [:get, :post, :delete, :put, :patch, :options, :head],
          :max_age => 0
      end
end

```
Is working great when I try to make AJAX requests using another website domain, but if someone try to access some resource directly via URL in the browser, ex: https://myclient1.com/my_protected_resource, or using tools like Advanced Rest Client is possible to access the data (JSON is this case). I'm working around it using a before_filter so I need to recheck the origin and send a 401 status code if the origin is not allowed.

Shouldn't Rack-Cors block this access too?

**Comment by cyu** [comment]
@rafael-tanaka This is a good question – my current line of thought on this is to keep the focus of this gem on the CORS spec and to keep access restriction out of scope.  As far as I know this isn't part of the CORS spec.  Also, the CORS spec shouldn't be considered as a security solution for these types of requests (someone can easily just changed the origin to be an accepted one).

Having said that, Rack-Cors does provide the tools you need to implement access restriction yourself.  The middleware adds a result object of key `rack.cors` into the Rack environment.  So you could inspect the result of the CORS spec with something like this (shooting from the hit here, didn't test this code):

```ruby
module Rack
  class BlockCORSFailures
    def initialize(app)
      @app  = app
    end
    def call(env)
      cors_result = env['rack.cors']
      if cors_result.nil? || cors_result.hit?
        return @app.call(env)
      else
        return [401, {}, ["Unauthorized"]]
      end
    end
end
```
As long as you put this middleware after `Rack::Cors` it should return a 401 of the CORS evaluation fails.

**Comment by rafael-tanaka** [comment]
Thanks!
