### ISSUE TITLE
The reason "Access-Control-Allow-Origin" is empty - `env[HTTP_ORIGIN]`?

### ISSUE THREAD

**Issue by ramontayag** [cyu/rack-cors#147]
I do not know why [some headers are not added if `env[HTTP_ORIGIN]` is not in the request env](https://github.com/cyu/rack-cors/blob/v1.0.1/lib/rack/cors.rb#L63), but maybe this is why a lot of people are not seeing things like `Access-Control-Allow-Origin` in the response?

- When I test locally using things like Postman, no `HTTP_ORIGIN` in the headers is set
- Does the origin even matter if rack-cors' `origins` is set to `'*'`?

I'm not familiar enough with how or when `HTTP_ORIGIN` or `HTTP_X_ORIGIN` should be set.

**Comment by cyu** [comment]
The Origin header is the trigger for the CORS spec. See sections 6.1 and 6.2 of the CORS spec:

https://www.w3.org/TR/cors/#cors-api-specifiation-request

**Comment by ramontayag** [comment]
I see. Ok thanks. I'll close this. Not sure many people know about this.
