### ISSUE TITLE
Allow Origin null

### ISSUE THREAD

**Issue by jkhulme** [cyu/rack-cors#155]
If I have a request like 

```
curl ’https://www.example.com/foo/bar/' \
-XGET \
-H ‘Accept: application/json, text/plain, */*’ \
-H ‘User-Agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Mobile/15A372’ \
-H ‘Origin: null’
```

In my config I can allow that request by having 

```
config.middleware.use Rack::Cors do
    allow do
    origins '*'
    resource '/foo/bar/',           headers: :any, methods: %i[ get put options ]
  end
end
```

But I don't want to have the allow '*' I would like to allow null somehow.  I have tried `'null'` and `/null/` but neither worked.  Is this something rack-cors can do.

**Comment by jkhulme** [comment]
![cors-request-response](https://user-images.githubusercontent.com/1363393/35616298-c3bcf028-066c-11e8-909e-06f7b3c79641.png)

**Comment by cyu** [comment]
This particular error is client side, not browser side.  https://meteatamel.wordpress.com/2012/05/15/origin-null-is-not-allowed-by-access-control-allow-origin/
