### ISSUE TITLE
communicate with react web api call with node server

### ISSUE THREAD

**Issue by RajaKorada** [cyu/rack-cors#160]
hi ,
i am getting  a error like 

**Failed to load http://localhost:2345/users: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**

when interacting with nodejs server port num :2345,

below attchment file is my json data..

![backend](https://user-images.githubusercontent.com/25481578/37554876-06245b2a-2a05-11e8-9a37-75c2bac90b7c.PNG)

i am calling that port num  in package.json of 3000 port
like below image
![package json file](https://user-images.githubusercontent.com/25481578/37554913-791e645e-2a05-11e8-8e9e-a0f1167c0e4d.PNG)

regards,
Rajendra.k

**Comment by cyu** [comment]
Please share your rack-CORS config

**Comment by cyu** [comment]
I'm closing this issue because there hasn't been any activity on this issue in a while.
