### ISSUE TITLE
pre-flight requests disconnect me from my application (non-rails)

### ISSUE THREAD

**Issue by BuonOmo** [cyu/rack-cors#179]
When I do a post CORS request (using [axios]). The OPTION request doesn't send session information. The issue I encounter is that after OPTION has been made, my Rack application looses track of the session and my user end up disconnected. Does it ring any bell?

I've been searching a lot for this issue. And I encountered a few topic discussing about the fact that it **is not axios role** to send cookie over an OPTION pre-flight request (for instance in [this discussion](https://github.com/axios/axios/issues/876). It should be the server that takes care of it.

[axios]: https://github.com/axios/axios

**Comment by cyu** [comment]
I'm closing this issue because there hasn't been any activity on this issue in a while.  Having said that, I do believe this has been correct in newer releases that returns `OPTIONS` without delegating to the app.
