### ISSUE TITLE
CORS problems with Rack-cors gem

### ISSUE THREAD

**Issue by publicidadeba** [cyu/rack-cors#200]
Having a hard time with permission. 
It works when I try to make a request to URLs(pages) and Ids from the same website, but when I tried to do the same with an external URL it didn´t work.

https://stackoverflow.com/questions/59796296/cors-problems-with-rack-cors-gem

**Comment by cyu** [comment]
Closing this as the link no longer works.  Please re-open with more information if the problem is still occurring.
