### ISSUE TITLE
jQuery Vulnerability

### ISSUE THREAD

**Issue by neryb** [cyu/rack-cors#212]
Whitesource flagged a vulnerability in rack-cors due the use of jQuery here:
https://github.com/cyu/rack-cors/blob/43a18824e03a37a97505df74099730bfceffa565/test/cors/runner.html#L9

Vulnerability:
https://github.com/advisories/GHSA-gxr4-xjj5-5px2

Resolution:
Update to jquery 3.5.0 or greater

**Comment by cyu** [comment]
Update example

**Comment by neryb** [comment]
Hi @cyu - I'm still seeing the reference to the older jquery in this example in `master`: https://github.com/cyu/rack-cors/blob/908ea29e1b0fdc4c6091ccb4eb92b6de1e370387/test/cors/runner.html#L9

Is the `runner.html` file being used at all?
