### ISSUE TITLE
Might be worth mentioning in the README that middleware order in Rails apps matters.

### ISSUE THREAD

**Issue by leppert** [cyu/rack-cors#23]
I ran into a scenario where enabling Rack::Cache interfered with Rack::Cors when configured  using `config.middleware.use Rack::Cors` (per the README). Inserting Rack::Cors at the top of the middleware stack using `middleware.insert 0, Rack::Cors` obviated the issue. It might be worth mentioning this is the README. You can see a related discussion here: https://github.com/diaspora/diaspora/pull/2990

**Comment by marcelobfonseca** [comment]
How can i position Rack::Cors in the stack middleware for a Non rails application?
