### ISSUE TITLE
[Quick Question] Is this a valid way to use wildcards in a configuration?

### ISSUE THREAD

**Issue by dep** [cyu/rack-cors#232]
To allow ports `3000` - `3009`:

```rb
allow do
  if !Rails.env.production?
    origins "http://localhost:300*"
    resource '*',
    headers: :any,
    methods: [:post],
    credentials: true
  end
end
```

**Comment by sandstrom** [comment]
I'd suggest closing this PR and open up the discussions tab on this repository. Then move questions like this to discussions.

**Comment by cyu** [comment]
@dep you should match origin using regular expressions instead.
