### ISSUE TITLE
Invite more maintainers

### ISSUE THREAD

**Issue by sandstrom** [cyu/rack-cors#234]
It would be great if this project had more maintainers, that could review PRs etc.

Maybe you can have a look among people that has previously contributed, and ask if anyone of them wants to help out?

Here are a few that should be fairly easy to act on:
- https://github.com/cyu/rack-cors/issues/233
- https://github.com/cyu/rack-cors/issues/231
- https://github.com/cyu/rack-cors/issues/232
- https://github.com/cyu/rack-cors/pull/228
- https://github.com/cyu/rack-cors/pull/219
- https://github.com/cyu/rack-cors/pull/184

A few other repo suggestions:

- Open the 'Discussions' tab on this repo, so you can move questions etc. out of issues, and into that tab.
- Remove the only existing wiki page, and hide the wiki (it's not used, better hide it).
- Remove the projects tab, not used.

(I'm not saying all of them should be fixed, may be better to close some without doing anything)

**Comment by cyu** [comment]
@sandstrom Thanks, for all your suggestions.

I've opened the Discussions tab and removed the Wiki and Project tabs.

I'd be happy to take on maintainers, but I'm not going to recruit for them.  I want to make sure contributors are willing to contribute long term. I think most contributors up to this point just scratches their itch and moves on (understandable really).  Considering how critical this middleware is, I don't want to risk inviting bad actors into this project.

If you have any other thoughts or ideas, I'd love to hear them
