### ISSUE TITLE
Support for Timing-Allow-Origin

### ISSUE THREAD

**Issue by bessey** [cyu/rack-cors#240]
From the [Resource Timing API](https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API) Docs

> Note: When [CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS) is in effect, many of these values are returned as zero unless the server's access policy permits these values to be shared. This requires the server providing the resource to send the [Timing-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Timing-Allow-Origin) HTTP response header with a value specifying the origin or origins which are allowed to get the restricted timestamp values.

While not strictly CORS, they are closely related enough that I feel that support for configuring this header would fit nicely in rack-cors. We at least would have identical values for our CORS origins and timing origins.

Open to a PR? Would we expect an API like

```
Rack::Cors do
  allow do
    origins CORS_REGEX
    allow_timing true
  end
end
```

or 

```
Rack::Cors do
  allow do
    origins CORS_REGEX
    timing_origins TIMING_SPECIFIC_REGEX
  end
end
```

**Comment by cyu** [comment]
Would be happy to take a PR.  I prefer the first option.

**Comment by bessey** [comment]
I meant outside the application. We're adding the headers in AWS cloudfront

**Comment by cyu** [comment]
Closing this issue for now.  Again, I will welcome a PR.
