### ISSUE TITLE
Tag for v2.0.0 is missing

### ISSUE THREAD

**Issue by MuhammadRazaAslam** [cyu/rack-cors#241]
@cyu 
According to the [changelog](https://github.com/cyu/rack-cors/blob/master/CHANGELOG.md), `v2.0.0` has been released but tag for `v.2.0.0` is missing.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/19810462/188363706-c87d1754-bb84-4c11-bcaf-a82077b10222.png">

**Comment by jbranchaud** [comment]
I noticed this as well and wasn't able to install v2.0.0 because of it:

```
Could not find gem 'rack-cors (~> 2.0.0)' in rubygems repository https://rubygems.org/ or installed
locally.
```

Is v2 in a pre-release phase or should it be available to use at this time?

**Comment by jbranchaud** [comment]
Looks like this is a duplicate issue of https://github.com/cyu/rack-cors/issues/233#issue-1130675285

**Comment by cyu** [comment]
Tagged RC1: https://github.com/cyu/rack-cors/issues/233#issuecomment-1242979594
