### ISSUE TITLE
Does not work with Rack 3.0.0

### ISSUE THREAD

**Issue by LarryNorth** [cyu/rack-cors#242]
This error occurs when using Rack 3.0.0: `Rack::Lint::LintError: uppercase character in header name: Access-Control-Allow-Origin`

It does not occur with Rack 2.2.4. Apparently Rack 3.0.0 enforces [the Rack Spec rule prohibiting uppercase letters in headers](https://github.com/rack/rack/blob/main/SPEC.rdoc#label-The+Headers).

I encountered this problem when running [Minimal Rack::Cors + Roda app](https://github.com/johnknapp/rack_cors_roda_test).

**Comment by cyu** [comment]
Thanks! Fixed here: a48a558
