### ISSUE TITLE
uninitialized constant Rack::Cors

### ISSUE THREAD

**Issue by blackjid** [cyu/rack-cors#26]
I'm having this issue when running a rails 3.2.12 app, it is running with unicorn on production environment
##### Here is the unicorn log.

``` ruby
/home/deploy/applications/wecul-api/releases/20130606154224/config/application.rb:72:in `<class:Application>'
:
uninitialized constant Rack::Cors
 (
NameError
)
    from /home/deploy/applications/wecul-api/releases/20130606154224/config/application.rb:12:in `<module:PeepoltvApi>'
    from /home/deploy/applications/wecul-api/releases/20130606154224/config/application.rb:11:in `<top (required)>'
    from /home/deploy/applications/wecul-api/releases/20130606154224/config/environment.rb:2:in `require'
    from /home/deploy/applications/wecul-api/releases/20130606154224/config/environment.rb:2:in `<top (required)>'
    from config.ru:4:in `require'
    from config.ru:4:in `block in <main>'
    from /home/deploy/applications/wecul-api/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
    from /home/deploy/applications/wecul-api/shared/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
    from config.ru:1:in `new'
    from config.ru:1:in `<main>'
    from /home/deploy/applications/wecul-api/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn.rb:44:in `eval'
    from /home/deploy/applications/wecul-api/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn.rb:44:in `block in builder'
    from /home/deploy/applications/wecul-api/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:722:in `call'
    from /home/deploy/applications/wecul-api/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:722:in `build_app!'
    from /home/deploy/applications/wecul-api/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:140:in `start'
    from /home/deploy/applications/wecul-api/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.2/bin/unicorn:126:in `<top (required)>'
    from bin/unicorn:16:in `load'
    from bin/unicorn:16:in `<main>'
E, [2013-06-06T21:20:28.718097 #7506] ERROR -- : reaped #<Process::Status: pid 30554 exit 1> exec()-ed
```
##### In my `Gemfile` I've added

``` ruby
gem 'rack-cors', :require => 'rack/cors'
```
##### In my `config/application.rb` I've added

``` ruby
config.middleware.use Rack::Cors do
  allow do
    origins '*'
    resource '*', :headers => :any, :methods => [:get, :post, :delete, :put, :options]
  end
end
```
### I'd already tryied
- Adding `require 'rack/cors'` in my `config/application.rb'
- I've tryied this in the rails console with this output

``` ruby
Loading production environment (Rails 3.2.12)
irb(main):001:0> Rack::Cors
 => Rack::Cors
```

**Comment by akinnunen** [comment]
Try adding:

require 'rack'
require 'rack/cors'

**Comment by mcka1n** [comment]
+1 @akinnunen It makes sense to add those requires before `use Rack::Cors do`. It worked for me.

**Comment by tknazn** [comment]
@akinnunen @mcka1n 
I encountered the following issue after adding requires into application.rb 
Please advise. 
`LoadError: cannot load such file -- rack/cors`

**Comment by promisepreston** [comment]
You just need to un-comment the Rack CORS gem in your Gemfile (gemfile.rb)

**# gemfile.rb**
`gem 'rack-cors'`

And also ensure that your cors initializer (cors.rb) is set this way
**# config/initializers/cors.rb**
```
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins 'localhost:4200'
    resource '*',
      headers: :any,
      methods: %i(get post put patch delete options head)
  end
end
```
**Hope this helps**

**Comment by cyu** [comment]
I'm closing this issue because there hasn't been any activity on this issue in a while.

**Comment by JessicaSew** [comment]
I'm having an issue when starting up my server with shotgun:
Boot Error
Something went wrong while loading config.ru

LoadError: cannot load such file -- rack/cors

**Comment by henriqueutsch** [comment]
I'm having this issue too and this works for me.

app_urls = ENV.fetch('APP_ORIGIN_URL', '').to_s.split(',').compact

if app_urls.present?
  require 'rack'
  require 'rack/cors'

  Rails.application.config.middleware.insert_before 0, Rack::Cors do
    allow do
      origins *app_urls

      resource '*',
               headers: :any,
               methods: [:get, :post, :put, :patch, :delete, :options, :head]
    end
  end
end

**Comment by henriqueutsch** [comment]
I'm having this issue too and this code resolv for me.

`
app_urls = ENV.fetch('APP_ORIGIN_URL', '').to_s.split(',').compact

if app_urls.present?
  require 'rack'
  require 'rack/cors'

  Rails.application.config.middleware.insert_before 0, Rack::Cors do
    allow do
      origins *app_urls

      resource '*',
               headers: :any,
               methods: [:get, :post, :put, :patch, :delete, :options, :head]
    end
  end
end
`

**Comment by henriqueutsch** [comment]
`app_urls = ENV.fetch('APP_ORIGIN_URL', '').to_s.split(',').compact

if app_urls.present?
  require 'rack'
  require 'rack/cors'

  Rails.application.config.middleware.insert_before 0, Rack::Cors do
    allow do
      origins *app_urls

      resource '*',
               headers: :any,
               methods: [:get, :post, :put, :patch, :delete, :options, :head]
    end
  end
end`
