### ISSUE TITLE
How to add Access-Control-Allow-Private-Network header in Option response?

### ISSUE THREAD

**Issue by galexw** [cyu/rack-cors#263]
I am working on a project that has a public network accessing my local environment via ngrok.

This causes the warning shown below in Chrome when the browser makes a preflight OPTION request.

![Screen Shot 2023-04-16 at 10 33 30 PM](https://user-images.githubusercontent.com/75999001/232364494-eca85356-ea77-4093-983e-52617ab58b3f.png)

It seems like I would have to add the header Access-Control-Allow-Private-Network. Is there a way to customize the headers returned? 

Link in the warning message:
https://developer.chrome.com/blog/private-network-access-update/?utm_source=devtools

**Comment by jotolo** [comment]
Hi @galexw , I am facing similar problem with a project I am working on. Did you manage to solve this? Could you explain how?
I am open to work on a PR to propose a new option for rack-cors to solve this. I would like first to check what was the approach you followed. Thanks
