### ISSUE TITLE
Specify entire subdomain

### ISSUE THREAD

**Issue by lloydmeta** [cyu/rack-cors#30]
Is there a way to specify that an entire subdomain (let's say api.example.com) should support CORS?

In particular, I'm looking to get this working with a Grape app mounted inside of Padrino...

**Comment by ramanbuttar** [comment]
`origins '*.example.com'` doesn't work. Wildcard is not being read as intended.

**Comment by buren** [comment]
@ramanbuttar is absolutely right. `*.example.com` will not allow the origin `test.example.com`

**Comment by ryanwjackson** [comment]
did this ever get resolved?  Is there a way around it?

**Comment by cyu** [comment]
Sorry - I don't know why I ever said you can do that.  Wildcard doesn't work, use a regular expression instead:

```ruby
config.middleware.use Rack::Cors do
  allow do
    origins /http:\/\/(.*?)\.example\.com/
    resource '*', :headers => :any, :methods => [:get, :post, :options]
  end
end
```

**Comment by imgarylai** [comment]
This is my regex example: 
```rb
/\Ahttps?:\/\/([a-zA-Z\d-]+\.){0,}example\.com\/?\z/
```

My example can match https and end up with top level domain. For example https://example.com.hello.info is not a valid domain.

**Comment by raywu** [comment]
Does origing have to match `http://` or `https://`? Matching `subdomain.example.com` has worked for me, but the doc is unclear.

`^(.*\.|)example\.com$` might work ([regexr](https://regexr.com/3qhbb))

**Comment by sakirtemel** [comment]
I've created a wiki for that as it might be useful for the other, later maybe it can be moved to README. Thanks @raywu for the regex and the link it was useful, I copied actually that one to the wiki

**Comment by imi56** [comment]
> Sorry - I don't know why I ever said you can do that. Wildcard doesn't work, use a regular expression instead:
> 
> ```ruby
> config.middleware.use Rack::Cors do
>   allow do
>     origins /http:\/\/(.*?)\.example\.com/
>     resource '*', :headers => :any, :methods => [:get, :post, :options]
>   end
> end
> ```

This will match `anything.example.com.co.in` as well which might not be desired expectation.
