### ISSUE TITLE
DOC: using this middleware for assets on heroku

### ISSUE THREAD

**Issue by GermanDZ** [cyu/rack-cors#32]
With Rails4 (maybe others too), heroku precompile the assets but, so… the middleware `ActionDispatch::Static` catch the request and respond very soon.

To define CORS for assets, don't use `config.middleware.use Rack::Cors`, instead use `config.middleware.insert_before ActionDispatch::Static, Rack::Cors` to ensure thar CORS are applied before responding as static.

A typical scenario is "fonts" served as assets from heroku (not S3 synched), with cloudfront (or not) in the middle, requested from firefox (cors required).

I think is only necessary to update the documentation with this particular case, to avoid a lot of tears and pain to other developers.

**Comment by 1updesign** [comment]
Thanks GermanDZ

**Comment by GermanDZ** [comment]
hey! @1updesign this is shocking… our company is called @1uptalent :)

**Comment by amba178** [comment]
this is the setting for my cors, and still does not work when deploying to heroku, any suggestions
config.middleware.insert_before ActionDispatch::Static, Rack::Cors, :debug => true, :logger => (-> { Rails.logger }) do
      allow do
        origins '*'

        resource '/cors',
          :headers => :any,
          :methods => [:post],
          :credentials => true,
          :max_age => 0

        resource '*',
          :headers => :any,
          :methods => [:get, :post, :delete, :put, :patch, :options, :head],
          :max_age => 0
      end
    end
