### ISSUE TITLE
rack-cors always prevents access when a browser gives "Origin: file://"

### ISSUE THREAD

**Issue by rsutphin** [cyu/rack-cors#53]
For `file://` origins, rack-cors always returns `Access-Control-Allow-Origin: null`. AFAICT, this means that it always tells the browser that a request made with the header `Origin: file://` is not permitted, even when you have configured `file://` as an allowed origin.

This is a problem because at least some browsers (tested on UIWebView on iOS 7.1, Safari 7.1) send `Origin: file://`. I see that other browsers (Firefox, e.g.) send `Origin: null` for XHR requests from `file://` pages. It seems like the solution to this would be to preserve the seen `Origin` header for this type of request and send the same thing back.

I'll put together a patch for this; please let me know if you see a problem with this approach.

**Comment by mpoisot** [comment]
Please add a section to the Readme about using "file://" as an acceptable origin. This is useful but not obvious.

**Comment by crystalneth** [comment]
This needs to be documented!

Who would think that to respond properly to a "null" Origin header, one needs to set the origin matcher to the exact string "file://"? I had to inspect the source to uncover this feature.

**Comment by fny** [comment]
I'm going to second this..

This issue made me thing that null is unsupported: https://github.com/cyu/rack-cors/issues/155

But here I see that it is.
