### ISSUE TITLE
Duplicate Access-Control-Allow-Origin Headers being returned

### ISSUE THREAD

**Issue by wedtm** [cyu/rack-cors#55]
When making a request to a CORS-enabled URL, rack-cors is adding both the `Access-Control-Allow-Origin: *` and `Access-Control-Allow-Origin: http://calling-server.example.com/` headers. This causes browsers to fail due to there being two headers.

What is going wrong here? Is this a configuration issue?

**Comment by sandeep45** [comment]
@wedtm did you decide to add `cors` headers in `nginx` or `rails`? Is there a way to have it at both places and have nginx overwrite the header rather than append a new one?

**Comment by wedtm** [comment]
@sandeep45 We decided to apply the headers with nginx. I'm not sure if you can have nginx override the CORS headers or not. If you find out, please let me know!
