### ISSUE TITLE
Question about preflight request behavior.

### ISSUE THREAD

**Issue by monfresh** [cyu/rack-cors#57]
Hi,

I'm a little confused about the expected behavior of the preflight request. If `REQUEST_METHOD` is `OPTIONS` and you also have  `Access-Control-Request-Method` set to something else, like `GET`, the HTTP status code in the response is 200 instead of 204.

I was under the impression that any `OPTIONS` request would always return a 204 as long as I have an appropriate route defined, as explained [here](https://github.com/cyu/rack-cors/issues/20#issuecomment-46523416).

If I don't include the `Access-Control-Request-Method` header,  then I get a 204 as expected, and I see this in the Rails log:

```
curl -i http://lvh.me:8080/api/locations -H "Origin: http://example.com" -X OPTIONS

Started OPTIONS "/api/locations" for 127.0.0.1 at 2014-10-14 15:09:23 -0400
Processing by Api::V1::CorsController#render_204 as JSON
  Parameters: {"unmatched_route"=>"locations"}
Can't verify CSRF token authenticity
Completed 204 No Content in 1ms (ActiveRecord: 0.0ms)
```

If I do include the `Access-Control-Request-Method` header and set it to something other than `OPTIONS`, then I get a 200 and I see this in the Rails log:

```
curl -i http://lvh.me:8080/api/locations -H "Origin: http://example.com" -H "Access-Control-Request-Method: GET" -X OPTIONS

Started OPTIONS "/api/locations" for 127.0.0.1 at 2014-10-14 15:14:44 -0400
```

This doesn't look right to me. Am I doing something wrong?

The GitHub API, for example, always returns a 204 if the request method is `OPTIONS`:

```
curl -i https://api.github.com/users/monfresh -H "Origin: http://travis-ci.org" -H "Access-Control-Request-Headers: Content-Type" -H "Access-Control-Request-Method: GET" -X OPTIONS
```

Also, I'm not sure if this standard behavior, but the GitHub API always returns the `Access-Control-Allow-Headers` even if the request does not include `Access-Control-Request-Headers` or `Access-Control-Request-Method`.

**Comment by cyu** [comment]
Closing this issue and leaving the response status code as 200 since the spec isn't clear.  It isn't worth breaking existing behavior.
