### ISSUE TITLE
How to add cors before cache

### ISSUE THREAD

**Issue by sandelius** [cyu/rack-cors#68]
When I add 
```ruby
insert_after 0, Rack::Cors, logger: Rails.logger do ...
```
in application.rb

and enable Rack::Cache in production.rb
```ruby
config.action_dispatch.rack_cache = true
```

Rack::Cache always ends up first in the middleware stack, and Cors second. If I understand the README correct Cors must be loaded before right? How do I do that?

EDIT: `insert_before` is what I need. dahhh :)  You can delete this. Thx

**Comment by cyu** [comment]
Ok, good.  I did cursory look into this, but couldn't figure out how Action Dispatch was inserting this into the middleware stack.  Closing this issue.
