### ISSUE TITLE
Expose only a subdomain?

### ISSUE THREAD

**Issue by JWesorick** [cyu/rack-cors#70]
I undertand that resource accepts a path, but how do I have CORS for only my api? `api.example.com`
```ruby
config.middleware.insert_before 0, "Rack::Cors" do
  allow do
      origins '*'
      resource 'api.example.com/*', :headers => :any, :methods => [:get, :post, :options]
   end
end
```

**Comment by DaveCollinsJr** [comment]
Hey did you ever have any luck with this?  I'm wrestling with an issue that only appears in iOS browsers and I think it has to do with subdomains as well.

**Comment by cyu** [comment]
@DaveCollinsJr What exactly is the issue on iOS browsers?

**Comment by cyu** [comment]
I've added this commit to address this scenario:
105166d

**Comment by cyu** [comment]
```ruby
config.middleware.insert_before 0, "Rack::Cors" do
  allow do
    origins '*'
    resource '/*',
        :headers => :any,
        :methods => [:get, :post, :options],
        :if => proc { |env| env['HTTP_HOST'] == 'api.example.com' }
   end
end
```
