### ISSUE TITLE
Access-Control-Allow-Headers not being returned

### ISSUE THREAD

**Issue by davidcelis** [cyu/rack-cors#80]
Hi; I have a simple Rack app (using the [Crepe](https://github.com/crepe/crepe) framework) and I have Rack::Cors set up like this:

``` ruby
use Rack::Cors do
  allow do
    origins '*'
    resource '*', {
      headers: %w[Authorization Content-Type],
      methods: %w[HEAD OPTIONS GET POST PUT PATCH]
    }
  end
end
```

I then have a simple health check endpoint:

``` ruby
class API < Crepe::API
  get(:health) { head :no_content }
end

run API
```

And when I make an OPTIONS request…

``` bash
% curl --include -H 'Origin: *' -X GET localhost:9292/health
HTTP/1.1 204 No Content
Cache-Control: max-age=0, private, must-revalidate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD, OPTIONS, GET, POST, PUT, PATCH
Access-Control-Max-Age: 1728000
Access-Control-Allow-Credentials: true
Vary: Origin
```

I would expect to also see `Access-Control-Allow-Headers: Authorization, Content-Type` but that header never gets set. Am I doing anything wrong with setup?

**Comment by koenrh** [comment]
That's because you should also send the `Access-Control-Request-Headers` header in the preflight request.

```bash
curl 'https://example.orgl/me' -X OPTIONS -H 'Access-Control-Request-Method: GET' -H 'Origin: https://example.org' -H 'Access-Control-Request-Headers: accept, x-authorization'
```

**Comment by DSalko** [comment]
I'm having the same problem when using jsfiddle from Chrome. 

`Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

In rails, I have  `headers: :any`. 

But `Access-Control-Allow-Headers` is never returned. Any suggestions?

**Comment by richardsondx-symbility** [comment]
-1 This issue is still happening

**Comment by cyu** [comment]
@DSalko @richardsondx-symbility I need more information to work with - what network activity looks like in chrome, what library you're using to make the request.

Also, you can configure rack-cors to return debug headers, which might give you an indication of what is going on.
