### ISSUE TITLE
Rails 3.2.22 not working with rack-cors

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [cyu/rack-cors#88]
Couldn't make it work with the rails instructions... See this ticket also:

http://stackoverflow.com/questions/18538549/cant-get-rack-cors-working-in-rails-application

**Comment by dyba** [comment]
@lichtamberg There isn't enough information in your comment or link to provide any direction on what issue you're having. I'm using this library right on an app built on Rails 3.2.22.2 and I have no problems.

**Comment by cyu** [comment]
I'm closing this issue because there hasn't been any activity on this issue in a while.

If you're still having problems. Please create a new issue and provide the specifics.
