### ISSUE TITLE
preflight checking from browser

### ISSUE THREAD

**Issue by anh87** [cyu/rack-cors#89]
Hi, 

I use rack-cors gem with newest version 0.4.0, Rails 4.2.1. This is the configuration in config.ru file

require 'rack/cors'
use Rack::Cors do
  allow do
    origins '_'
    resource '_',
        :headers => :any,
        :methods => [:get, :post, :delete, :put, :options],
        :max_age => 1728000
  end
end

I implemented an API system to support Angularjs(front-end) to upload photo to s3. These first steps are ok but when the S3 redirect to the server I receive an error "XMLHttpRequest cannot load https://BUCKET-S3.amazonaws.com/. The request was redirected to 'http://LOCALHOST_IP:3000/api/v1/uploads/success?auth_token=.....', which is disallowed for cross-origin requests that require preflight." 

When I 'chromium-browser --disable-web-security', it can be redirected :)) 

How can I fix it? Anyone can help me?

**Comment by cyu** [comment]
This is a browser issue and not an issue with rack-core.  Closing.

More info: https://stackoverflow.com/questions/34949492/cors-request-with-preflight-and-redirect-disallowed-workarounds

**Comment by cyu** [comment]
Closing this ticket as
