### ISSUE TITLE
no Set-Cookie header on POST requests

### ISSUE THREAD

**Issue by Biggless** [cyu/rack-cors#90]
I don't know is my problem related to rack-cors but I need to start somewhere :)

When I set session via GET requests - Set-Cookie is sent and I can see cookie in the browser console.
But when I try to set session via POST request - there is no Set-Cookie header in response.

Where I'm wrong?

**Comment by Biggless** [comment]
Here is an example:
App sources: https://github.com/Biggless/corscheck
Running app: https://pure-coast-6857.herokuapp.com/
JSFiddle: https://jsfiddle.net/5ncyecp0/6/

**Comment by cyu** [comment]
Try bypassing the CSRF checks by adding this to the controller:

`skip_before_action :verify_authenticity_token`

**Comment by Biggless** [comment]
Yeah! Thanks a lot!

**Comment by fishermand46** [comment]
Is there any other way around this? `skip_before_action :verify_authenticity_token` seems kind of risky to me.
