### ISSUE TITLE
Can't use Rails Console when suing Cors middleware (with Rbenv)

### ISSUE THREAD

**Issue by bobintornado** [cyu/rack-cors#99]
Under my case, if `application.rb` file uses Cors with following codes 

```ruby
config.middleware.use Rack::Cors do
  allow do
    origins "*"
    resource "*", headers: :any, methods: [:get, :post, :put, :delete, :options]
  end
end
```

I can't fire up my rails console, and I am getting following error messages. (I am using Rbenv)

```
/Users/Bob/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/stack.rb:112:in `push': can't modify frozen Array (RuntimeError)
```

Once I remove the codes, I could fire up console as usual. 

Anyone encounters similar issues before?

**Comment by cyu** [comment]
Do you have the rest of the backtrace?

**Comment by bobintornado** [comment]
Hey @cyu, the bug mysteriously disappears after I move the project from my Dropbox to Desktop. 

I could fire up the console as normal and it seems nothing had ever happened. :/
